version: '3.9'

services:
  qea-pg:
    image: postgres:16.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: qeadb
    volumes:
      - ./data/pg:/data/postgres

  qea:
    build: .
    depends_on:
     - "qea-pg"
    links:
     - "qea-pg"
    container_name: qea
    restart: always
    entrypoint: sleep infinity
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data