name: ci-auth-workflow
on: 
    pull_request:
        branches:
            - development
jobs:
    check-application:
        strategy:
            matrix:
                node-version: [19.x]
        runs-on: ubuntu-latest
        env:
          NODE_ENV: test
          JWT_SECRET: mysecret
          VERIFY_EMAIL_SECRET: verifyemail
          RESET_PASSWORD_SECRET: resetpassword
          DYNAMODB_TABLE: Users
          DYNAMODB_ACCESS_KEY: 
          DYNAMODB_SECRET_KEY: 
          DYNAMODB_REGION: local
          DYNAMODB_ENDPOINT: http://localhost:8000
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm run test-unit
            - run: npm run build

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1 
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                push: true
                tags: pedronx/auth:latest
      
