name: ci-qea-workflow
on: 
    pull_request:
        branches:
            - development
jobs:
    check-application:
        strategy:
            matrix:
                node-version: [19.x]
        runs-on: ubuntu-latest
        env:
          NODE_ENV: test
          JWT_SECRET: mysecret
          RESET_PASSWORD_SECRET: resetpassword
          DATABASE_URL: postgresql://postgres:docker@qea-pg:5432/qeadb?schema=public
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm run test-unit
